### ISSUE TITLE
Path to INI is ignored

### ISSUE THREAD

**Issue by spaceeinstein** [CookiePLMonster/GXT-Builder#2]
It seems that the INI file must be in the same directory as the builder regardless of the path given in the command line. With `gxtbuilder.exe dir\american.ini` for example, the builder does not read the INI file in the dir directory but will always read the INI file that is in the same directory as it.

**Comment by CookiePLMonster** [comment]
I'll take a look, but do note currently paths from the INI file are not relative to its path but rather to working directory path - I probably should change that. What do you think?

**Comment by spaceeinstein** [comment]
Can you show me an example of the command? My example directory that didn't work looks like this:
```
current_dir
| dir
| | EN
| | | MAIN
| | \ \- MAIN.txt
| |- american.ini
| \- charmap.txt
\- gxtbuilder.exe
```
The one that did work looks like this:
```
current_dir
| EN
| | MAIN
| \ \- MAIN.txt
|- american.ini
|- charmap.txt
\- gxtbuilder.exe
```

**Comment by CookiePLMonster** [comment]
Yes this is correct. My build script does this

```
cd GXT
gxtbuilder american.ini -vc
```

and **EN** dir comes straight in the GXT directory - just like in your second example.

That said, you are right - The first example should work too (as long as american.ini in there contains paths relative to **dir** directory) and this should probably be classified as a bug. I'm looking into this as we speak, which explains why I'm replying so fast =)
